server:
  port: 8888
configclient:
  ribbon:
    eureka:
      enable: true
    ServerListRefreshInterval: 15000
    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
eureka:
  instance:
    hostname: ribbonclient
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
          defaultZone: http://localhost:8761/eureka
